### PR TITLE
Change token access to craft headers

### PR DESCRIPTION
**Pull request by internetztube**
First of all, I would like to thank you for the repository. It helped me a lot.

I had the problem that I didn't get the variable $_SERVER['REDIRECT_HTTP_AUTHORIZATION'] set with regular browser tools (XHR).
In my eyes, it makes more sense to use the HTTP header directly here.

If you don't agree with me I would be happy about a browser XHR example.

### CODE REVIEW

**Comment by hubertprein** [comment]
Sorry for the late reply, but thanks for the PR!

I agree with the change, just noticed that the `bool $rememberMe = false` added parameter is never used? Remove before merging?

Edit: Noticed I've used an unknown variable.. Thanks for the fix!

**Comment by internetztube** [comment]
Thanks!

**Comment by internetztube** [comment]
Can you bump the version so the changes are available via composer?

**Comment by hubertprein** [comment]
Done.

**Pull request merged**
